import { createSlice } from "@reduxjs/toolkit";

// Define initial state for the revenue slice
const initialState = {};

// Create revenue slice using createSlice method
export const revenueSlice = createSlice({
  name: "revenue",
  initialState,
  reducers: {
    // Reducer for requesting 24-hour revenue data
    get24hrsRevenueRequest: (state) => {
      state.isLoading = true;
    },
    // Reducer for successful retrieval of 24-hour revenue data
    get24hrsRevenueSuccess: (state, action) => {
      state.isLoading = false;
      state.revenue = action.payload;
    },
    // Reducer for failed retrieval of 24-hour revenue data
    get24hrsRevenueFailure: (state, action) => {
      state.isLoading = false;
      state.error = action.payload;
    },
  },
});

// Export actions generated by revenue slice
export const {
  get24hrsRevenueRequest,
  get24hrsRevenueSuccess,
  get24hrsRevenueFailure,
} = revenueSlice.actions;

// Export the revenue reducer
export default revenueSlice.reducer;
